language: go

dist: trusty

go:
- 1.9
- tip

install:
  - rm -rf src/github.com/exoscale/egoscale
  - git clone -b dev --single-branch https://github.com/exoscale/egoscale src/github.com/exoscale/egoscale
  - make devdeps

script:
  - make
  - test `gofmt -s -d src/github.com/exoscale/terraform-provider-exoscale | tee -a /dev/fd/2 | wc -l` -eq 0
  - test `bin/golint github.com/exoscale/terraform-provider-exoscale | tee -a /dev/fd/2 | wc -l` -eq 0
  - make vet
